language: c
source_key:
  LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBOFFwZ1hXdVBx
  MkJYN3dvQUk1K1kyODk0QzE3bzFnZVFKRUphRy9ZbHJtS2IzMXJ6CmpOYmZiSWxJMDBGOGpuRTkx
  TnU2dEZHYThPOVpBKzhZVlhxL1hSZHl2aWcyQmhwcEIza0g1RHRQZzVYT1lwYVEKRTg0K2cwbnhq
  amcxYTlrOVI5K1NsK1VrY21TMGZPeWZRWTBMTmpXcGtnRmJaR216VzFSZ0MvenpudjNGMGZuSgp5
  V0hjUE5JZlphVC8zSmRCSmc5QllLVmhvVWdDYkx3VHBZSEZvZ0VGWGliYy9PMVoyWVUwc3BlL1lo
  dzdocHlDCmJvbXFsREN3VytrQnIzQ3RYUzd2am5VT25DYXp1bXRMYThaU3Y2czlQMXE1MEI2dG1v
  OG5ibit4bzlvWHZ2SFEKdkNRaUl5cWRLTmgxQTdkVG03ZWNTaTcraG45N2VEZEp5NmlNc3dJREFR
  QUJBb0lCQUFhU2pOd2ZRYlNmbE9ZOAp0SkpFR012dGxVMWlFaUU3NVk5SGkrTjFTOE84aHBtSmhs
  aVJ4MWZUU253UUxoQklRREpjcDNPaFFnTk4wM1NMCkFYUGJPL3FTMkJzZFI1UFZCb1lnbzdseWNK
  R2E5UnkxRkVxbDlnaG9iTUMvQVozbU40aU5MUmNkTldnMUhNTEgKUlBScG55T2tSUEpwUFErNDNo
  NGdaOW9MMUt6Q0d5Ukk1MCtvcXJvRHAvWHMzN0ttQ3ZtbUhFdjdjbWtocmNrdwpUcWdqeXhJSXpP
  UnRaRW9zaHhsWmVocXRDUUMyTndOdTVodlYyczhWVHBzS1V6VlVNVzJSWTRNc1loT2Y1a3FyCkQ5
  TzlUWVhhbjZVZDhxdFpYTUZ0LzVxc1J2dFluSzVrTjBQQWJxR0YzUHB4YTdKRXpPU1RodUZRWndL
  d2Z5dlMKcEFKWncrRUNnWUVBLzhkeG9rMFQzMDlGWkF1RXR3OWdIRGJxRjJQSDdRZFRkL2kvckpl
  QnlrQ2lVVUx6YUtvZgo4K3NxR3ZqSnlrbEo0Q0JwNTZJR0UrUDBCL1VVM3ZtalNacWE1cjE0dE5i
  Vk9BRHBsTnQ0RnJNbHhxd01VOWEvClZJWVpqUWxZZ2NtNlI4d2VKSFZTWHk1SktHZXpjNmhRRlh4
  S0UxYTVqUk5OeEI3akJMOFllTkVDZ1lFQThUK3MKZE1PQnBnUkYwc05NNUNrVWg2NnExSmZuMjJC
  L0ZRQmRSQzNodVlIRHRjcnZ2QU9iZ1hRMzhBUWlobVZLS0x5WQpHSjNSU09pcDNUYTBUQVNKTy9n
  S0VRdHpFeVRmdjlWa0lacmpVODZkQjNIOFY3L0hWbU5KTUVuemhVbCtOdk1nCnkxNDJzK3ZJNHls
  ZzNkK3prMDUvem5RUUhUT29vNjFOL1pDdGprTUNnWUJ6U0E4ZFdhUVZTQU04Zmp5SXpYTkMKQkRZ
  cDZKMFpaZTNtNnNScEk3Z3Awa3ZXV0ZpZzJkeWc4V0wrMlJjS0IxSTJwQ1ZYY3gxT0piVzlTR2Jw
  d0pZcAovSGJJZktsRXlIYzlVSnYyclp4SWp1SDkwMW1UQi8wZ09YaVdxcG1ybGFKUjdkdkFEdWpi
  WVY4enlObUd6VnVhCjgzUG5sM1QxOHJkZ0o1T21kZ0t2b1FLQmdCSlY2WkNTVDJkRHlkN0Q4ek1n
  SUN4VHpTNE5RWlQ5MTRyTUZVcWEKUmg2b1N5eWsrT1dNVEtSaEplTTdIVGlqdUNneWRVamhyY2Ro
  ejQ4OW1pUnc3OUU3LzkvZHcrZy9sRFhyVFFuMAowTFJNN3NoakZHL0M1cTZkS3pIZFhRSFRYU0Zt
  QnljTnlSQ1JxaG9CeWhmeTZaNFhpRVV6c3duVkpFc1VYK29XCnRlb3JBb0dBYlNtSFdWck9FSzV0
  Z0ttSVVObVJ0OXJJd1JSL2tWaW5GcHpidlQvK0dxOGQ4OVFvVG5uUHZnU3EKT1F2RXdVODlFMjZD
  dmo1TUUxUFhURDlaT1RXRm9xNGNwb0VKd3VZNHNMSTA3T0J2OGtuRVQ4d0RaUXNIZjZ1LwpleEhD
  MUV0dTZrZWpaRHIzOFY3bTJuWUNoa2VGZTk3cjBjaXJxdkJUMko0VEQ4NFl6SWM9Ci0tLS0tRU5E
  IFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
git:
  submodules: false
before_install:
  - sudo add-apt-repository -y 'deb http://ppa.launchpad.net/avsm/ppa/ubuntu raring main'
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y ocaml opam binfmt-support
  - (mkdir llvm; cd llvm; curl http://fehu.whitequark.org/files/llvm-3.4~svn188438.tbz2 | tar xjv)
  - sudo dpkg -i llvm/*_amd64.deb
  - cp .travis.key ~/.ssh/id_rsa
  - git submodule update --init
install:
  - opam install sexplib extlib menhir ulex js_of_ocaml
script:
  - export OCAMLPATH=/usr/lib/ocaml/llvm-3.4/
  - ./scripts/build.sh
