language: c
before_install:
  - sudo add-apt-repository ppa:avsm/ppa
  - sudo apt-get install ocaml opam
install:
  - opam install sexplib extlib menhir ulex js_of_ocaml
script:
  - build.sh
  - test.sh
